# Use the latest Ubuntu as the base image
FROM ubuntu:latest

# Update APT repository
RUN apt-get update

# Upgrade currently installed software through APT
RUN apt-get upgrade -y

# Set the command to be run when the container starts
CMD echo "Hello, World!"
