version: '3'
services:
  front-end:
    build:
      context: ./softy-pinko-front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6

  back-end:
    build:
      context: ./softy-pinko-back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    deploy:
      replicas: 2 # Scale the back-end service to 2 replicas

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
